[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
  '@chainlinkAg=lib/chainlink-brownie-contracts/contracts/src/v0.8/interfaces/'
  
]
ffi =true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
